### ISSUE TITLE
GH source code asset for release is missing vendor folder

### ISSUE THREAD

**Issue by jeffpaul** [10up/embed-block-figma#25]
### Describe the bug

Checking the "source code" asset on https://github.com/10up/figma-block/releases/tag/0.2.0 will show an error when trying to activate the plugin.  This may be due to a missing vendor directory, but checking to see what else might be amiss is worthwhile to ensure the next release will be activatable.

### Steps to Reproduce

.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by dkotter** [comment]
So I think we can wait on this one until we actually deploy to WordPress.org, as we only attach the final release asset once that happens (see this step: https://github.com/10up/embed-block-figma/blob/develop/.github/workflows/wordpress-plugin-deploy.yml#L33).

The zip attached there right now is the one GitHub adds automatically to all releases and it won't contain any of our built assets. The actual zip we care about will only be attached once a proper release goes out to WordPress.org so once that happens, we should check to ensure a valid release is attached and if so, we can close this out at that point. If it doesn't work, we can investigate further.

**Comment by jeffpaul** [comment]
@dkotter the dotorg svn repo has been approved, so perhaps we do another minor release that functionally doesn't change anything but does deploy to dotorg to get fully published there?

**Comment by dkotter** [comment]
> @dkotter the dotorg svn repo has been approved, so perhaps we do another minor release that functionally doesn't change anything but does deploy to dotorg to get fully published there?

Yep, sounds good to me

**Comment by dkotter** [comment]
Checking on the [latest release](https://github.com/10up/embed-block-figma/releases/tag/0.3.1), I do see the proper release asset being attached there and in downloading that, I do see all expected files, including the built files.
